apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-oein
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0008-tenant/ci1t-830-0008-app/devfile-sample-oein@sha256:f05ccfbfcee94c122ef87267020d221b71c732f05f58935f709ce4dc6de4a675
        name: my-nodejs
        resources: {}
status: {}
